version: 2.1

executors:
  android-docker:
    docker:
      - image: circleci/android:api-33

jobs:
  build:
    executor: android-docker
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Build
          command: ./gradlew assembleDebug
      - run:
          name: Run Tests
          command: ./gradlew test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
